#!/bin/python3


import sys

arr = []

for arr_i in range(6):
    arr_t = [int(arr_temp) for arr_temp in input().strip().split(' ')]
    arr.append(arr_t)

v = 0    
h = 0
sum_of_lines = 0
current = -82
largest = -82

#row loop
for i in range(4):
    h = 0
    #column loop
    for j in range(4):
        line1 = arr[v][h:(h+3)]
        line2 = [arr[v+1][(h+1)]]
        line3 = arr[v+2][h:(h+3)]
        line_list = [line1,line2,line3]

        for line in line_list:
            sum_of_lines = sum_of_lines + sum(line)


        if sum_of_lines > current:
            current = sum_of_lines

        largest = max(current,largest)
        #print("Current sum of lines is:", sum_of_lines,
              #"Current largest is:",current,
              #"Overall largest is:",largest)
        sum_of_lines = 0
        h = h + 1
    v = v + 1 
print(largest)
    


